### PR TITLE
Add Database Seeding Script and API get photos endpoint

### PR DESCRIPTION
**Pull request by hugoxiong5**
Trello cards: 
https://trello.com/c/wFTc5ilP/186-create-database-for-photos-api

https://trello.com/c/tSwMnc0p/241-seed-database-of-reviews-module

Sorry, this is a big pull request, I forgot to make a different branch for the server code. This pull request replaces the last one, which I closed.

Jest unit tests for both the seeding script and the API get photos endpoint are now working.

### CODE REVIEW

**Review by martinsung00 — CHANGES_REQUESTED** [review]
Dummy Request Change -- Do not change anything as this is a test.

**Comment by hugoxiong5** [comment]
Why do you think I'm a dummy?

**Comment by hugoxiong5** [comment]
Hello!!!

**Comment by hugoxiong5** [comment]
I made a couple @ comments, does anyone see them?

**Review by martinsung00 — CHANGES_REQUESTED** [review]
Files under seeder has been reviewed. The separation of concerns is great.
However resetDatabase() method in seed-function.js is declared but never exported or used. The name for seed-s3.js is a little confusing, I'm unsure what this does. Might need claification on that. Lastly, in the early stages of development, hard-coding the data is great, but you may have to automate the generation of data. I.e if the data exceeds 100, hardcoding 100 products may be difficult. The variables are intuitive, and so are the methods.

**Review by martinsung00 — APPROVED** [review]
Files under server has been reviewed. No issues regarding the files or tests.

**Comment by martinsung00** [comment]
Files under server has been reviewed. No issues regarding variable naming, placement of files, level of clarity, tests, and size of functions.

**Review by martinsung00 — CHANGES_REQUESTED** [review]
Tests are inutiive, easy to understand. No unused variables or poorly named variables. However, if possible tests should fall under a test folder so it's not placed in the middle of your other js files. If it isn't possible is there a reason why?

**Comment by hugoxiong5** [comment]
> Files under seeder has been reviewed. The separation of concerns is great.
> However resetDatabase() method in seed-function.js is declared but never exported or used. The name for seed-s3.js is a little confusing, I'm unsure what this does. Might need claification on that. Lastly, in the early stages of development, hard-coding the data is great, but you may have to automate the generation of data. I.e if the data exceeds 100, hardcoding 100 products may be difficult. The variables are intuitive, and so are the methods.

The resetDatabase method is used in the seed-db.test.js file (Jest unit test).

The seed-s3.js file will be used to upload photos to AWS S3, I haven't implemented that yet.

I agree, when the placeholder data is replaced, I will create a function to auto-generate the data, specifically, the urls.

> However, if possible tests should fall under a test folder so it's not placed in the middle of your other js files. If it isn't possible is there a reason why?

Yes, according to some docs, it's preferred to place a unit test next to the file it's testing. https://create-react-app.dev/docs/running-tests/ "We recommend to put the test files (or __tests__ folders) next to the code they are testing so that relative imports appear shorter"

Thanks for your comments and the review! I appreciate it.

**Pull request merged**
